# Generated by Django 5.1.3 on 2025-03-19 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionGastos', '0002_alter_gasto_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='monto_total',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
