# Generated by Django 5.1.3 on 2025-03-19 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionGastos', '0003_remove_presupuesto_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presupuesto',
        ),
    ]
